name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [24]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - name: Setup node env 🏗
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules 📦
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # - name: Install latest npm
      #   run: npm install -g npm@latest

      - name: Install dependencies 👨🏻‍💻
        run: npm clean-install

      - name: Run linter 👀
        run: npm run lint

      - name: Run tests 🧪
        run: npm run test
